### ISSUE TITLE
Is it possible to allow for a new version of voilà?

### ISSUE THREAD

**Issue by jrklasen** [danielfrg/jupyter-flex#124]
The Voilà version is set to be <0.3 is there a reason for this restriction?

**Comment by danielfrg** [comment]
Mostly because they were making big changes and I wanted to keep things tight at that point.

I imagine updating would require some changes on the package so might take a minute to update. I will try to test soon

**Comment by jmp75** [comment]
I think I bumped into an issue related to this, adding `jupyter-flex` from conda-forge to an environment; voila <0.3 seem to use a deprecated feature of `jinja2 `:

```text
ImportError: cannot import name 'contextfilter' from 'jinja2' (/blah/envs/bm/lib/python3.9/site-packages/jinja2/__init__.py)
```

where:

```text
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
```

I am trying to install the `jupyter-flex` python package from source in dev mode, see if I can help. I am following the contribution instructions, but am a bit unsure of what I am doing  (unfamiliar with the javascript world).

**Comment by isabelizimm** [comment]
Adding onto this issue-- I've enjoyed using `jupyter-flex`, but loosening the `voila` requirements would be super helpful! I had a lot of troubles getting an install with no dependency conflicts, primarily due to the voila constraint.

**Comment by danielfrg** [comment]
Library is updated to work with voila 0.4 but I need to update some docs.
Hopefully today I can release a quick update

**Comment by danielfrg** [comment]
`0.9.1` has been released. It should solve this issue
